# Generated by Django 4.1.6 on 2023-02-26 16:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_comment_ticket_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Task',
        ),
    ]
