# Generated by Django 4.1.6 on 2023-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_ticket_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments_list', to='task.comment'),
        ),
    ]
